# Generated by Django 5.0 on 2023-12-09 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=30)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('deadline_date', models.DateTimeField()),
                ('level_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_task', to='app.level')),
                ('status_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_task', to='app.status')),
            ],
        ),
    ]
